name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей и сборка бэкенда
        run: |
          cd  warehouse-server
          npm ci
          npm run build
          cd ..

      - name: Архивирование (исключая node_modules)
        run: |
          cd  warehouse-server
          tar --exclude='node_modules' --warning=no-file-changed -czf ../backend.tar.gz .
          cd ..

      - name: Запись .env локально
        run: echo "${{ secrets.ENV_PROD }}" > .env

      - name: Копирование .env на сервер
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: ".env"
          target: "/srv/apps/backend/"

      - name: Копирование архива проекта на сервер
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: "backend.tar.gz"
          target: "/srv/apps/"

      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            echo "===> Переключаемся в директорию проекта"
            cd /srv/apps

            echo "===> Распаковываем backend в папку backend"
            rm -rf backend
            mkdir backend
            tar -xzf backend.tar.gz -C backend
            rm backend.tar.gz

            echo "===> Перемещаем .env в нужное место"
            mv backend/.env backend/.env.production

            echo "===> Обновляем и перезапускаем контейнеры"
            docker compose down
            docker compose build
            docker compose up -d

            echo "===> Проверка статуса контейнеров"
            docker compose ps

            echo "===> Последние логи"
            docker compose logs --tail=100
