name: Build and Deploy Backend

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/bartik369/backend:latest .
          docker push ghcr.io/bartik369/backend:latest
          
      - name: Залить .env на сервер.
        uses: appleboy/ssh-action@v1
        with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        port: 22
        script: |
         cat <<EOF > /srv/apps/backend/.env
         ${{ secrets.ENV_PROD }}
         EOF

      - name: Deploy on remote server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u "${{ secrets.GHCR_USERNAME }}" --password-stdin
            docker pull ghcr.io/${{ github.repository_owner }}/backend:latest
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 5000:5000 --restart unless-stopped \
              --env-file /srv/apps/backend/.env \
              ghcr.io/${{ github.repository_owner }}/backend:latest
