name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Write .env file locally
        run: echo "${{ secrets.ENV_PROD }}" > .env

      - name: Copy .env to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: ".env"
          target: "/srv/apps/backend/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          command_timeout: 10m
          script: |
            echo "===> Переключаемся в директорию проекта"
            cd /srv/apps/backend

            echo "===> Обновляем репозиторий"
            git pull origin main

            # Добавленный шаг: очистка предыдущей сборки
            echo "===> Удаляем старую сборку и зависимости"
            rm -rf dist node_modules .npm

            echo "===> Останавливаем контейнеры"
            docker compose down

            echo "===> Собираем образы (с очисткой кэша)"
            docker compose build --no-cache

            echo "===> Запускаем контейнеры в фоне"
            docker compose up -d

            echo "===> Проверка статуса контейнеров"
            docker compose ps

            echo "===> Вывод логов (последние 100 строк)"
            docker compose logs --tail=100
