name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          command_timeout: 50m
          script: |
            echo "===> Переключаемся в директорию проекта"
            cd /srv/apps/backend

            echo "===> Обновляем репозиторий"
            git pull origin main

            echo "===> Создаём .env.production из GitHub Secret"
            cat <<EOF > .env.production
            ${{ secrets.ENV_PROD }}
            EOF

            echo "===> Останавливаем контейнеры"
            docker compose down

            echo "===> Собираем образы"
            docker compose build

            echo "===> Запускаем контейнеры в фоне"
            docker compose up -d

            echo "===> Проверка статуса контейнеров"
            docker compose ps

            echo "===> Вывод логов (последние 100 строк)"
            docker compose logs --tail=100
