name: Deploy Backend to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Упаковка backend кода
        run: tar -czf backend.tar.gz . --exclude=node_modules

      - name: Отправка архива на сервер
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: "backend.tar.gz"
          target: "/srv/apps/"

      - name: Отправка .env на сервер
        run: echo "${{ secrets.ENV_PROD }}" > .env

      - name: Копирование .env на сервер
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          source: ".env"
          target: "/srv/apps/backend/"

      - name: Распаковка и перезапуск контейнеров
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          command_timeout: 20m
          script: |
            echo "Распаковываем backend в нужную директорию"
            mkdir -p /srv/apps/backend
            tar -xzf /srv/apps/backend.tar.gz -C /srv/apps/backend

            echo "Удаляем архив"
            rm /srv/apps/backend.tar.gz

            echo "Переходим в корень проекта"
            cd /srv/apps

            echo "Пересобираем и перезапускаем контейнеры"
            docker compose down
            docker compose build --no-cache
            docker compose up -d
