name: Deploy Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Установка зависимостей и сборка бэкенда
        run: |
          npm ci --legacy-peer-deps
          npm run build

      - name: Запись .env локально
        run: echo "${{ secrets.ENV_PROD }}" > .env

      - name: Копирование проекта на сервер через SCP
        run: |
         echo "${{ secrets.DEPLOY_SSH_KEY }}" > key.pem
         chmod 600 key.pem
         scp -i key.pem -r -o StrictHostKeyChecking=no ./* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/srv/apps/backend/


      - name: Деплой на сервер через SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          port: 22
          script: |
            echo "===> Переключаемся в директорию проекта"
            cd /srv/apps/backend

            echo "===> Переименовываем .env в .env.production"
            mv .env .env.production

            echo "===> Обновляем и перезапускаем контейнеры"
            docker compose down
            docker compose build
            docker compose up -d

            echo "===> Проверка статуса контейнеров"
            docker compose ps

            echo "===> Последние логи"
            docker compose logs --tail=100
